// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDidCCt94DJpq0m0NvgUxMD-0pE_5_O2SY',
    appId: '1:892879784845:web:719e2cfbe2be7c3c384bc4',
    messagingSenderId: '892879784845',
    projectId: 'motiveme-6c8da',
    authDomain: 'motiveme-6c8da.firebaseapp.com',
    databaseURL: 'https://motiveme-6c8da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motiveme-6c8da.firebasestorage.app',
    measurementId: 'G-7M02SBSTV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhMcuS84NdaLxwqTnwUyJUbtrtb6IFXfU',
    appId: '1:892879784845:android:9ccfc3650b7f8a65384bc4',
    messagingSenderId: '892879784845',
    projectId: 'motiveme-6c8da',
    databaseURL: 'https://motiveme-6c8da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motiveme-6c8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMpfYHzjrEbqtlHIc6UFu3VKjHOpaRXA',
    appId: '1:892879784845:ios:d828efb2edbc2792384bc4',
    messagingSenderId: '892879784845',
    projectId: 'motiveme-6c8da',
    databaseURL: 'https://motiveme-6c8da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motiveme-6c8da.firebasestorage.app',
    iosClientId: '892879784845-jhhpqjifnmnvvqtqnddopllmer8kldmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.motiveMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiMpfYHzjrEbqtlHIc6UFu3VKjHOpaRXA',
    appId: '1:892879784845:ios:d828efb2edbc2792384bc4',
    messagingSenderId: '892879784845',
    projectId: 'motiveme-6c8da',
    databaseURL: 'https://motiveme-6c8da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motiveme-6c8da.firebasestorage.app',
    iosClientId: '892879784845-jhhpqjifnmnvvqtqnddopllmer8kldmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.motiveMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDidCCt94DJpq0m0NvgUxMD-0pE_5_O2SY',
    appId: '1:892879784845:web:8d88afdeb5f65a77384bc4',
    messagingSenderId: '892879784845',
    projectId: 'motiveme-6c8da',
    authDomain: 'motiveme-6c8da.firebaseapp.com',
    databaseURL: 'https://motiveme-6c8da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'motiveme-6c8da.firebasestorage.app',
    measurementId: 'G-L9WTEPVFRL',
  );
}
